[package]
name = "periodic_do"
version = "0.1.0"
edition = "2021"


[dependencies]
# utilities
chrono = { version = "0.4" }
log = "0.4"
thiserror = "1.0"

tokio = { version = "1.15", features = ["sync", "time", "rt"] }
async-trait = "0.1"
